CREATE DATABASE Senatur_Manha;

USE Senatur_Manha;

CREATE TABLE TiposUsuario(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(100) UNIQUE NOT NULL
	);

CREATE TABLE Cidades(
	IdCidade INT PRIMARY KEY IDENTITY,
	NomeCidade VARCHAR(255)
	);

CREATE TABLE Usuarios(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Email VARCHAR(255) UNIQUE NOT NULL,
	Senha VARCHAR(255) NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TiposUsuario(IdTipoUsuario)
	);

CREATE TABLE Pacotes(
	IdPacote INT PRIMARY KEY IDENTITY,
	NomePacote VARCHAR(255) NOT NULL,
	Descricao TEXT NOT NULL,
	DataIda DATE NOT NULL,
	DataVolta DATE NOT NULL,
	Valor DECIMAL (18,2) NOT NULL,
	Ativo BIT DEFAULT (1) NOT NULL,
	IdCidade INT FOREIGN KEY REFERENCES Cidades(IdCidade)
	);